# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "creators"
name = "Creators"
url = "/creators"

[main.params]
icon = "writing"

[[social]]
identifier = "patreon"
name = "Patreon"
url = "https://patreon.com"

[social.params]
icon = "brand-patreon"
