# Decap CMS Configuration
backend:
  name: github
  repo: manifold-creator-collective/mcc-web
  branch: master
  base_url: https://sveltia-cms-auth.logan-8c2.workers.dev

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}>
    update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}>
    delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}>
    uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}>
    deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}>
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}>

# Better Decap + Bridge logo (optional)
logo_url: https://manifoldcollective.com/images/logo-full-black.png

# Add site links in DecapCMS (optional)
site_url: https://manifoldcollective.com

# Media and Public Folders
media_folder: "assets/uploads" # Media will be stored in this folder in the repo
public_folder: "/images/uploads" # The src attribute for uploaded media

# Optional: publish mode
# publish_mode: editorial_workflow # Enables drafts and editorial workflow

# Collections - customize these based on your site's structure
collections:
  - name: "creator" # Used in routes, e.g., /admin/collections/author
    label: "Creators" # Used in the UI
    folder: "content/creators" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, using just the slug
    fields: # The fields for each document
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Avatar", name: "avatar", widget: "image", required: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      
      # Common Skills Section
      - label: "Common Skills"
        name: "common_skills"
        widget: "select"
        multiple: true
        required: false
        hint: "Select from common TTRPG skills that will have custom icons"
        options:
          - "Game Design"
          - "Adventure Design"
          - "Mechanics Design"
          - "Map Design"
          - "DM/GM"
          - "Worldbuilding"
          - "Character Design"
          - "Narrative Design"
          - "Balancing"
          - "Encounter Design"
          - "Editing"
          - "Playtesting"
          - "Art"
          - "Illustration"
          - "Layout"
          - "Writing"
          - "Event Organization"
          - "Data Analytics"
          - "Voice Actor"
      
      # Other Skills Section for custom entries
      - label: "Other Skills"
        name: "other_skills"
        widget: "list"
        required: false
        hint: "Add additional skills not found in the common skills list"
        min: 0
        max: 15
        add_to_top: true
        field: {label: "Skill", name: "skill", widget: "string"}
      
      # Projects Section
      - label: "Projects"
        name: "projects"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        hint: "Add the creator's projects"
        fields:
          - {label: "Project Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "URL", name: "url", widget: "string", required: false}
          - {label: "Status", name: "status", widget: "select", options: ["Available", "In Progress", "Coming Soon", "Archive"], default: "Available"}
          - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      
      # Currently Open For Section
      - {label: "Currently Open For", name: "open_for", widget: "markdown", required: false, hint: "Describe what kind of work or collaboration the creator is currently available for"}
      
      - label: "Social Media"
        name: "social"
        widget: "list"
        summary: "{{fields.platform}} - {{fields.url}}"
        required: false
        fields:
          - {label: "Platform", name: "platform", widget: "select", options: ["facebook", "instagram", "github", "linkedin", "patreon", "itchio", "discord", "youtube", "twitch", "x", "bluesky", "mastadon", "website", "email", "other"], default: "website"}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Display Text", name: "display_text", widget: "string", required: false, hint: "Optional text to display instead of the URL"}

  - name: "category" # Used in routes, e.g., /admin/collections/category
    label: "Categories" # Used in the UI
    folder: "content/categories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, using just the slug
    fields: # The fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - label: "Badge Style"
        name: "style"
        widget: "object"
        fields:
          - {label: "Background Color", name: "background", widget: "color", default: "#2a9d8f"}
          - {label: "Text Color", name: "color", widget: "color", default: "#fff"}
      - {label: "Body", name: "body", widget: "markdown", required: false, hint: "Optional content for the category page"}

  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "creator"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        required: false
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "category"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        required: false
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
