name: Build and Deploy Hugo Site
on:
  # Run daily at midnight UTC
  schedule:
    - cron: '0 0 * * *'
  
  # Run when a webhook is triggered
  repository_dispatch:
    types: [deploy]
    
  # Optional: Run when changes are pushed to main branch
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (if used)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      
      - name: Install Tailwind CSS Standalone CLI
        run: |
          # Download the latest version of the Tailwind CSS standalone CLI
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          
          # Move to a location in PATH
          sudo mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
          
          # Verify installation
          tailwindcss --help
          
          # Print current directory structure for debugging
          echo "Current directory structure:"
          ls -la
      
      - name: Build site
        run: hugo --minify
      
      # Alternative SSH setup with appleboy's action
      - name: Deploy to VPS via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: manifoldcollective.com
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: public/
          target: /var/www/manifoldcollective/
          strip_components: 1
          
      - name: Set permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: manifoldcollective.com
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: chmod -R 755 /var/www/manifoldcollective/