name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - 'package.json'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check.outputs.version_changed }}
      new_version: ${{ steps.check.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if version was bumped
        id: check
        run: |
          git fetch
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          if echo "$CHANGED_FILES" | grep -q "package.json"; then
            OLD_VERSION=$(git show HEAD~1:package.json | grep '"version":' | cut -d'"' -f4)
            NEW_VERSION=$(grep '"version":' package.json | cut -d'"' -f4)
            if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
              echo "Version changed from $OLD_VERSION to $NEW_VERSION"
              echo "version_changed=true" >> $GITHUB_OUTPUT
              echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            else
              echo "Version unchanged"
              echo "version_changed=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "package.json not modified"
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            dukerupert/mcc-web:${{ needs.check-version.outputs.new_version }}
            dukerupert/mcc-web:latest
          build-args: |
            PUBLIC_DIRECTUS_URL=${{ secrets.PUBLIC_DIRECTUS_URL }}
